services:
  db:
    image: postgres:14.8
    container_name: crypto_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Serviço opcional: Streamlit (caso deseje no futuro)
  # streamlit:
  #   build:
  #     context: ./streamlit_app
  #     dockerfile: Dockerfile
  #   container_name: crypto_streamlit
  #   ports:
  #     - "8501:8501"
  #   networks:
  #     - airflow_net
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./streamlit_app:/app
  #   env_file: .env
  
volumes:
  postgres_data:

networks:
  airflow_net:
    driver: bridge