services:
  db:
    image: postgres:14.8
    container_name: crypto_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  # Porta externa 5433 para evitar conflito com a 5432 usada pelo Airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: crypto_streamlit
    ports:
      - "8501:8501"
    networks:
      - airflow_net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./streamlit_app:/app
    env_file: .env

networks:
  airflow_net:
    driver: bridge

volumes:
  postgres_data: